### ISSUE TITLE
[Help] - NameError : name 'ftfy' is not defined

### ISSUE THREAD

**Issue by fan9704** [Wan-Video/Wan2.1#327]
as title I follow Wan2.1 HuggingFace Page to build my personal Wan2.1 model
but when I running model an exception come up

### Code

```python
import torch
from diffusers import AutoencoderKLWan, WanPipeline
from diffusers.utils import export_to_video

# Available models: Wan-AI/Wan2.1-T2V-14B-Diffusers, Wan-AI/Wan2.1-T2V-1.3B-Diffusers
model_id = "Wan-AI/Wan2.1-T2V-1.3B-Diffusers"
vae = AutoencoderKLWan.from_pretrained(model_id, subfolder="vae", torch_dtype=torch.float32)
pipe = WanPipeline.from_pretrained(model_id, vae=vae, torch_dtype=torch.bfloat16)
pipe.to("cuda")

prompt = "A cat walks on the grass, realistic"
negative_prompt = "Bright tones, overexposed, static, blurred details, subtitles, style, works, paintings, images, static, overall gray, worst quality, low quality, JPEG compression residue, ugly, incomplete, extra fingers, poorly drawn hands, poorly drawn faces, deformed, disfigured, misshapen limbs, fused fingers, still picture, messy background, three legs, many people in the background, walking backwards"

output = pipe(
    prompt=prompt,
    negative_prompt=negative_prompt,
    height=480,
    width=832,
    num_frames=81,
    guidance_scale=5.0
).frames[0]
export_to_video(output, "output.mp4", fps=15)
```

### Enviroment

Platform: Windows 11
Python: 3.12.5
Depencies

```toml
requires-python = ">=3.12,<4.0"
dependencies = [
    "accelerate (>=1.6.0,<2.0.0)",
    "transformers (>=4.51.2,<5.0.0)",
    "scipy (>=1.15.2,<2.0.0)",
    "torch (>=2.6.0,<3.0.0)",
    "torchvision (>=0.21.0,<0.22.0)",
    "torchaudio (>=2.6.0,<3.0.0)",
    "diffusers (>=0.33.1,<0.34.0)",
]

[[tool.poetry.source]]
name = "pytorch-gpu-126"
url = "https://download.pytorch.org/whl/cu126"
priority = "explicit"


[tool.poetry.dependencies]
torch = {source = "pytorch-gpu-126"}
torchvision = {source = "pytorch-gpu-126"}
torchaudio = {source = "pytorch-gpu-126"}
```

### Log

```log
Loading pipeline components...:   0%|          | 0/5 [00:00<?, ?it/s]
Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]
Loading checkpoint shards:  50%|█████     | 1/2 [00:03<00:03,  3.42s/it]
Loading checkpoint shards: 100%|██████████| 2/2 [00:04<00:00,  2.15s/it]
Loading pipeline components...:  60%|██████    | 3/5 [00:04<00:02,  1.34s/it]
Loading checkpoint shards:   0%|          | 0/5 [00:00<?, ?it/s]
Loading checkpoint shards:  20%|██        | 1/5 [00:05<00:20,  5.05s/it]
Loading checkpoint shards:  40%|████      | 2/5 [00:09<00:14,  4.69s/it]
Loading checkpoint shards:  60%|██████    | 3/5 [00:13<00:08,  4.36s/it]
Loading checkpoint shards:  80%|████████  | 4/5 [00:17<00:04,  4.36s/it]
Loading checkpoint shards: 100%|██████████| 5/5 [00:20<00:00,  4.17s/it]
Loading pipeline components...: 100%|██████████| 5/5 [00:25<00:00,  5.16s/it]
Traceback (most recent call last):
  File "C:\Users\XXX\OneDrive\Desktop\snapiza\backend\t2v.py", line 14, in <module>
    output = pipe(
             ^^^^^
  File "C:\Users\XXX\OneDrive\Desktop\snapiza\backend\.venv\Lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XXX\OneDrive\Desktop\snapiza\backend\.venv\Lib\site-packages\diffusers\pipelines\wan\pipeline_wan.py", line 486, in __call__
    prompt_embeds, negative_prompt_embeds = self.encode_prompt(
                                            ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XXX\OneDrive\Desktop\snapiza\backend\.venv\Lib\site-packages\diffusers\pipelines\wan\pipeline_wan.py", line 230, in encode_prompt
    prompt_embeds = self._get_t5_prompt_embeds(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XXX\OneDrive\Desktop\snapiza\backend\.venv\Lib\site-packages\diffusers\pipelines\wan\pipeline_wan.py", line 154, in _get_t5_prompt_embeds
    prompt = [prompt_clean(u) for u in prompt]
              ^^^^^^^^^^^^^^^
  File "C:\Users\XXX\OneDrive\Desktop\snapiza\backend\.venv\Lib\site-packages\diffusers\pipelines\wan\pipeline_wan.py", line 91, in prompt_clean
    text = whitespace_clean(basic_clean(text))
                            ^^^^^^^^^^^^^^^^^
  File "C:\Users\XXX\OneDrive\Desktop\snapiza\backend\.venv\Lib\site-packages\diffusers\pipelines\wan\pipeline_wan.py", line 79, in basic_clean
    text = ftfy.fix_text(text)
           ^^^^
NameError: name 'ftfy' is not defined

Process finished with exit code 1
```

Did anyone ran out same problem how to deal with that
